name: 批量获取Google Android内核

on:
  workflow_dispatch:
  
jobs:
  fetch_kernels:
    name: Fetch and Compress Kernel Sources
    runs-on: ubuntu-latest
    timeout-minutes: 240  # 延长超时时间
    
    strategy:
      # 使用矩阵策略处理多个版本组合
      matrix:
        include:
          - { android: 11, kernel: 5.4 }
          - { android: 12, kernel: 5.4 }
          - { android: 13, kernel: 5.10 }
          - { android: 14, kernel: 5.15 }
          - { android: 14, kernel: 6.1 }
          - { android: 15, kernel: 6.1 }
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        
      - name: Setup directory
        run: |
          # 为每个版本组合创建独立工作目录
          mkdir -p android-kernel
          cd android-kernel
          mkdir ${ANDROID_KERNEL_DIR}
          echo "WORKING_DIR=$(pwd)/${ANDROID_KERNEL_DIR}" >> $GITHUB_ENV
          
        env:
          ANDROID_KERNEL_DIR: android${{ matrix.android }}-kernel${{ matrix.kernel }}
      
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip p7zip-full pigz git-lfs
          sudo pip3 install -U repo
          
          # 配置git避免中断
          git config --global user.email "3025009453@qq.com"
          git config --global user.name "yy520h"
      
      - name: Initialize repo for Android ${{ matrix.android }}, Kernel ${{ matrix.kernel }}
        run: |
          cd ${{ env.WORKING_DIR }}
          repo init -u https://android.googlesource.com/kernel/manifest \
            -b common-android${{ matrix.android }}-${{ matrix.kernel }}
      
      - name: Sync source code
        run: |
          cd ${{ env.WORKING_DIR }}
          repo sync -j$(nproc) -c --no-tags --optimized-fetch --force-sync \
            --fail-early-when-manifest-invalid
        
        # 重试机制，谷歌源有时不稳定
        continue-on-error: true
        timeout-minutes: 45
      
      - name: Compress source to ZIP
        run: |
          cd ${{ env.WORKING_DIR }}
          
          # 确保文件系统完全写入
          sync
          # 避免文件变化导致的压缩错误
          find . -type f -exec touch {} +
          
          # 使用7z高压缩率打包
          7z a -mx=8 -mmt=on ../${{ env.ANDROID_KERNEL_DIR }}.zip *
          
          echo "ARCHIVE_NAME=${{ env.ANDROID_KERNEL_DIR }}.zip" >> $GITHUB_ENV
          echo "ARCHIVE_PATH=$(pwd)/../${{ env.ARCHIVE_NAME }}" >> $GITHUB_ENV
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: ${{ env.ARCHIVE_PATH }}
          retention-days: 7
