name: Android内核驱动编译

on:
  workflow_dispatch:
    inputs:
      android_version:
        description: '安卓版本(10-15)'
        required: true
      kernel_version:
        description: '内核版本(4.4-6.6)'
        required: true
      driver_name:
        description: '驱动程序模块名称(hack.ko)'
        required: true
      target_arch:
        description: '目标架构 (aarch64, x86_64, etc.)'
        required: true
        default: 'aarch64'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        
      - name: 复制文件
        run: |
          mkdir kerneldriver
          mv ./code/*.h ./code/*.c ./code/Makefile kerneldriver/
          
      - name: 配置环境工具repo
        run: |
          sudo curl -L https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
          sudo chmod a+x /usr/local/bin/repo

      - name: 开始拉取内核源码
        run: |
          mkdir -p android-kernel && cd android-kernel
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android${{ github.event.inputs.android_version }}-${{ github.event.inputs.kernel_version }}
          repo sync -j$(nproc) -c --no-tags --optimized-fetch --force-sync

      - name: 复制你的驱动文件到目录
        run: |
          cd android-kernel
          cp -r ../kerneldriver common/drivers

      - name: 设置环境
        run: |
          cd android-kernel
          echo "obj-y += kerneldriver/" >> common/drivers/Makefile

      - name: 适配编译 GKI
        if: ${{ github.event.inputs.android_version > 13 }}
        run: |
          cd android-kernel
          MODULE_NAME="drivers/kerneldriver/${{ github.event.inputs.driver_name }}"
          
          awk -i inplace -v module="$MODULE_NAME" '
            BEGIN { added=0 }
            /_COMMON_GKI_MODULES_LIST =  $$/ { in_list=1 }
            in_list && /$$ / {
              if (!added) {
                print "    \"" module "\","
                added=1
              }
              in_list=0
            }
            in_list && !added {
              if (module < $0) {
                print "    \"" module "\","
                added=1
              }
            }
            { print }
          ' common/modules.bzl
          
      - name: 适配13 系统以下的版本
        if: ${{ github.event.inputs.android_version <= 13 }}
        run: |
          cd android-kernel
          echo "drivers/kerneldriver/${{ github.event.inputs.driver_name }}" >> common/android/gki_aarch64_modules
      - name: 修改缓冲区大小
        run: |
          cd android-kernel
          find . -type f -name "Makefile*" -exec sed -i 's/-Wframe-larger-than=[0-9]*/-Wframe-larger-than=4096/g' {} +
          grep -q "FRAME_WARN" common/Makefile || echo 'KBUILD_CFLAGS += -Wframe-larger-than=4096' >> common/Makefile

      - name: 设置环境
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential flex bison libssl-dev libelf-dev bc python-is-python3
      - name: 开始编译
        run: |
          cd android-kernel
          if [ ${{ github.event.inputs.android_version }} -le 13 ]; then
            BUILD_CONFIG=common/build.config.gki.${{ github.event.inputs.target_arch }} LTO=thin build/build.sh -j32
            OUTPUT_PATH="out/android${{ github.event.inputs.android_version }}-${{ github.event.inputs.kernel_version }}/dist"
          else
            echo "使用Bazel构建系统为Android ${{ github.event.inputs.android_version }}"
            tools/bazel run //common:kernel_${{ github.event.inputs.target_arch }}_dist
            OUTPUT_PATH="out/kernel_${{ github.event.inputs.target_arch }}"
          fi
          echo "OUTPUT_PATH=$OUTPUT_PATH" >> $GITHUB_ENV
        continue-on-error: true
      
      - name: 编译结束开始尝试上传文件
        id: upload_driver
        uses: actions/upload-artifact@v4.6.2
        if: success() || failure()
        with:
          name: kernel-driver-${{ github.event.inputs.target_arch }}
          path: |
            $(find android-kernel/${{ env.OUTPUT_PATH }} -type f -name "${{ github.event.inputs.driver_name }}" -o -name "${{ github.event.inputs.driver_name }}.*")
      - name: 检查是否有输出目标.ko文件
        if: failure() && steps.upload_driver.outcome != 'success'
        run: |
          echo "编译错误：未找到驱动文件，请检查编译过程是否正确。"
        shell: bash
